apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: crystallm-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crystallm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crystallm-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: crystallm-role
subjects:
- kind: ServiceAccount
  name: crystallm
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: crystallm
  name: crystallm-sa-secret
type: kubernetes.io/service-account-token
